#!/usr/bin/env python
# encoding: utf-8

def configure(conf):
    pass

def build(bld):
    lv2_base = 'gx_cabinet'

    bld.lv2(
        lv2_base = lv2_base,
        source   = ['gxcabinet.cpp'],
        includes = ['../faust','./', '../DSP', '../DSP/tube_tables'],
        use = ['LV2CORE','GX_CONVOLVER'],
        ldscript = 'gx_cabinet.lds',
        mapfile = "gx_cabinet.map",
        )
    bld.lv2_gui(
        lv2_base = lv2_base,
        source   = ' gx_cabinet_ui.cpp',
        includes = ['../xputty/header','../xputty/header/widgets','../xputty/resources','../xputty/lv2_plugin'],
        use = ['xcairo','X11', 'CAIRO','LV2CORE'],
        )
    bld.lv2_ttl(
        lv2_base = lv2_base,
        )
