#!/usr/bin/env python
# encoding: utf-8

def configure(conf):
    pass

def build(bld):
    lv2_base = 'gx_shimmizita'

    bld.lv2(
        lv2_base = lv2_base,
        source   = ['gx_shimmizita.cpp'],
        includes = ['../faust','./', '../DSP'],
        use = ['LV2CORE'],
        )
    bld.lv2_gui(
        lv2_base = lv2_base,
        source   = ' gx_shimmizita_ui.cpp',
        includes = ['../xputty/header','../xputty/header/widgets','../xputty/resources','../xputty/lv2_plugin'],
        use = ['xcairo','X11', 'CAIRO','LV2CORE'],
        )
