#!/usr/bin/env python
# encoding: utf-8

def configure(conf):
    pass

def build(bld):
    lv2_base = 'gxautowah'

    bld.lv2(
        lv2_base = lv2_base,
        source   = ['gxautowah.cpp'],
        includes = ['./', '../DSP'],
        cxxflags=['-fvisibility=hidden','','','-Wl,--exclude-libs,ALL'],
        use = ['LV2CORE'],
        )
    bld.lv2_gui(
        lv2_base = lv2_base,
        source   = ' gx_autowah_ui.cpp',
        includes = ['../xputty/header','../xputty/header/widgets','../xputty/resources','../xputty/lv2_plugin'],
        cxxflags=['-fvisibility=hidden','','','-Wl,--exclude-libs,ALL'],
        use = ['xcairo', 'CAIRO','LV2CORE'],
        )
