#!/usr/bin/env python
# encoding: utf-8

def configure(conf):
    pass

def build(bld):
    lv2_base = 'gxmetal_head'

    bld.lv2(
        lv2_base = lv2_base,
        source   = ['gxmetal_head.cpp'],
        includes = ['../faust','./', '../DSP', '../DSP/tube_tables'],
        use = ['LV2CORE','GX_CONVOLVER','GX_RESAMPLER'],
        )
    bld.lv2_gui(
        lv2_base = lv2_base,
        source   = ' gxmetal_head_ui.cpp',
        includes = ['../xputty/header','../xputty/header/widgets','../xputty/resources',],
        use = ['xcairo','X11', 'CAIRO','LV2CORE'],
        )
    bld.lv2_ttl(
        lv2_base = lv2_base,
        )
