name: build

on: [push]

#defaults:
  #run:
  #  shell: bash

jobs:
  ####################
  build-windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
    - name: Prepare MSys2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-7zip
          git
          base-devel
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-pkg-config
          mingw-w64-x86_64-meson
          mingw-w64-x86_64-libsigc++
          mingw-w64-x86_64-lv2
          mingw-w64-x86_64-eigen3
          mingw-w64-x86_64-fftw
          mingw-w64-x86_64-libffi
          mingw-w64-x86_64-libsndfile
          mingw-w64-x86_64-cairo

    - name: Check out sources
      uses: actions/checkout@v3.3.0
      with:
        submodules: recursive

    - name: build
      run: |
        cd trunk
        ./tmbuild.sh

    - name: zip
      run: cd trunk/_bin ; 7z a -mx9 ../../plugin.7z lv2 ; cd ../..

    - uses: actions/upload-artifact@v3.1.2
      with:
        name: guitarix-lv2-plugins-win64.7z
        path: plugin.7z

