name: build

on: [push]

#defaults:
  #run:
  #  shell: bash

jobs:
  ####################
  build-windows:
    runs-on: windows-latest

    defaults:
      run:
        #shell: msys2 {0}
        #shell: /msys64/msys2_shell.cmd -mingw64 -where . -c {0}
        #shell: \msys64\msys2_shell.cmd -mingw64 -where . -c {0}
        #shell: /msys64/mingw64 bash -c {0}
        shell: /msys64/mingw64 bash

    steps:
    - name: Add msys2 to PATH
      shell: pwsh
      run: |
        echo "c:\msys64;%PATH%" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8
        
      #echo "c:\msys64" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        
    #- name: Check out sources
    #  uses: actions/checkout@v3.3.0
    #  with:
    #    submodules: recursive

    - name: check MSys2
      run: |
        pwd
        find
